### ISSUE TITLE
please update to freedesktop runtime 21.08

### ISSUE THREAD

**Issue by xpseudonym** [flathub/net.sourceforge.jpdftweak.jPdfTweak#11]
Thank you for keeping this great app available

**Comment by felipehw** [comment]
I tried some alternatives (https://github.com/flathub/net.sourceforge.jpdftweak.jPdfTweak/pull/12) but every new build that I made runs in my machine with a different look and feel from the actual build.

The actual build:
![Screenshot from 2022-03-18 17-44-40](https://user-images.githubusercontent.com/4523897/159080798-b3f1cecf-7e9c-49ac-980b-9dd361e8f220.png)

The new build:
![screenshotfrom2022-03-1817-45-03](https://user-images.githubusercontent.com/4523897/159081072-4d464028-9bbb-4f8b-9da9-087366e82205.png)

I believe the actual build is using the "Metal" Java Look and feel and the new build is using GTK Java Look and feel.
I don't have much contact with Java.
I like the aesthetics of GTK Java Look and feel but it destroys usability of this software because we can't differentiate enabled from disabled UI elements. E.g.: look at disabled checkbox "Interleave documents in blocks of".

If you can give some help here ...

**Comment by xpseudonym** [comment]
I have installed the version from flathub and I can confirm it looks like the second 'new build' version above - and I can also confirm that the check box and text entry box 'Interleave documents in blocks of' don't differentiate between an enabled and disabled state.

Thank you.

**Comment by bbhtt** [comment]
You have to run it with `flatpak run --env=XDG_CURRENT_DESKTOP=null net.sourceforge.jpdftweak.jPdfTweak` so that it doesn't pick up the GTK aesthetics. This doesn't having anything to do with the runtime update.

![image](https://github.com/flathub/net.sourceforge.jpdftweak.jPdfTweak/assets/62639087/371db46f-4827-43bb-8826-d840be3365d8)

**Comment by felipehw** [comment]
Closed by #14

**Comment by felipehw** [comment]
@bbhtt Thanks for your help. I put this env in the manifesto.
@xpseudonym It is finally updated.
