### ISSUE TITLE
Why you changed the permissions ?!

### ISSUE THREAD

**Issue by Nokia808** [flathub/net.sourceforge.jpdftweak.jPdfTweak#5]
Hi. Why you changed the permissions ?! Now, I can not open PDF files located outside "Desktop", "Downloads", & "Documents" ! Why this ? What is the idea about this limitation ?! jPDFTweak is not like WINE front-end to be afraid from it & make this limitation !

Please can you give me a logical cause for this change.

**Comment by felipehw** [comment]
We know this app is safe.
I could just give permission to access the whole filesystem (like in a world without Flatpaks).
But if everyone to this, the Flatpak permission system would be of little help (because, supposedly, almost every app in Flathub is safe anyway).
The idea is that for people who don't know a software the default permissions given to it be reasonable. (And access to all home content is warned as "High" at Gnome Software with a noisily "!").

jPDF doesn't need access to the home directory that contains a lot of sensible configuration, etc. files. jPDF only needs to access a bunch of PDF files to work on them. It is reasonable to think that these files are in the *Documents*, *Downloads*, or *Desktop* dirs of the user. Or, if it is not the case, that will be very easy for the user to move them to these folders while works in these files.

The current configurations, aside "be more reasonable" at the POV of "confidence about a unknow app" to a new user, allows to users with *Documents*, *Downloads* or *Desktop* dirs in other partitions access this content. In the previous setup, the user just could access every folder inside home **but not** *Documents*, *Downloads* or *Desktop* xdg-folders configured outside of the partition of `/home`.

If the user is a more advanced one that doesn't care about "xdg-dirs" conventions of a "normal Desktop" ... he can invoke `flatpak override --user --filesystem=/.../  net.sourceforge.jpdftweak.jPdfTweak` or use Flatseal GUI.
